Small fix for auto thread_type
Revert auto threadtype when looking for frame due to :
File "av/stream.pyx", line 132, in av.stream.Stream.__setattr__
File "av/codec/context.pyx", line 623, in av.codec.context.CodecContext.thread_type.__set__
RuntimeError: Cannot change thread_type after codec is open.